version: '3'

services:
  node-service:
    build: 
      context: ./
    ports:
      - "3003:3001" 
    depends_on:
      - mongo-db
    environment:
      - DATABASE_HOST=mongo-db
      # DATABASE_HOST=host ip

      mongo-db:
    image: mongo:latest
    restart: always


